### ISSUE TITLE
error in baseline index

### ISSUE THREAD

**Issue by rockyplum** [Edouard99/Stress_Detection_ECG#1]
in `get_ecg_f_from_file `, there is a mistake in
```
ECG_neutral = np.array(df["signal"]["chest"]["ECG"][indice_neutral[0]:indice_neutral[-1]*700][:,0]) #Baseline
```
You should not `* 700`.

**Comment by Edouard99** [comment]
Why shouldn't I ? It's been a long time since I did not use this project but as I remember it worked perfectly fine with that
