### ISSUE TITLE
dimension of data error and warning of cuda of my 4090

### ISSUE THREAD

**Issue by DJL1n** [Edouard99/Stress_Detection_ECG#2]
![image](https://github.com/user-attachments/assets/650e0d39-1788-4520-88f4-8069887ab107)
I have completed the dataset creating,and then run the model.ipnb i shows the error as image
I'am fresh about,can you give some guidance

**Comment by Edouard99** [comment]
Hey, idk where you see a trouble in the dimension of data in the error, then as it is told in the error, which you should fully read, you have installed a version of pytorch incompatible with your 4090, go to their link, try a web research or feed it to chatgpt.

**Comment by DJL1n** [comment]
yeah I made mistakes,it's nothing with the dimention. But Idk the version of cuda should I choose, gpt give the little help...I just wanna use all the same with your env
here is the env of the machine
<img width="1054" alt="image" src="https://github.com/user-attachments/assets/d1199321-215a-4d2d-9cbe-524f8cadcddd" />
plz tell me what to change directly

**Comment by Edouard99** [comment]
How did you install pytorch ? It seems that you installed an incompatible version, you need to install the right pytorch version :
For an NVIDIA RTX 4090 GPU with compute capability sm_89, you should install a compatible version of PyTorch that supports CUDA 11.8 or later. Here’s the recommended PyTorch version setup:

    PyTorch Version: Install the latest stable version of PyTorch.
    CUDA Toolkit: Use CUDA 11.8 or 12.x if supported.
    Installation Command:

    pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Why This Version?

    RTX 4090 Support: The RTX 4090 is based on the Ada Lovelace architecture, requiring CUDA 11.8+ for full support.
    sm_89 Compatibility: CUDA 11.8 and later fully support the sm_89 architecture.

**Comment by DJL1n** [comment]
thanks alot for your guidance, everything runs well now
